import json

from django.core.management.base import BaseCommand
from django.core.serializers.json import DjangoJSONEncoder

from server.api import api


class Command(BaseCommand):
    """Export OpenAPI schema generated by django-ninja."""

    help = 'Export OpenAPI schema to a file'

    def add_arguments(self, parser):
        parser.add_argument(
            '--file',
            '-f',
            default='docs/openapi.json',
            help='Path to output schema file',
        )

    def handle(self, *args, **options):
        schema = api.get_openapi_schema()
        output = options['file']
        with open(output, 'w', encoding='utf-8') as fh:
            json.dump(schema, fh, indent=2, cls=DjangoJSONEncoder)
        self.stdout.write(self.style.SUCCESS(f'OpenAPI schema exported to {output}'))
