# Generated by Codex on 2025-07-07
from django.db import migrations


class Migration(migrations.Migration):
    """Remove BlogPost model."""

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
