# Generated by Django 5.1.13 on 2025-10-13 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('minio_bucket', models.CharField(default='document-processing', max_length=255)),
                ('minio_key', models.CharField(help_text='Path in MinIO bucket', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('current_step', models.CharField(blank=True, choices=[('UPLOAD', 'Upload'), ('PDF_TO_IMAGES', 'PDF to Images'), ('ML_INFERENCE', 'ML Inference'), ('DRAW_BOUNDING_BOXES', 'Draw Bounding Boxes'), ('TEXT_EXTRACTION', 'Text Extraction'), ('ASSEMBLE_GRAPH', 'Assemble Graph')], max_length=50, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_step', models.CharField(blank=True, max_length=50, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('document_graph', models.JSONField(blank=True, help_text='Complete document structure graph', null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Main pipeline Celery task ID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'documents_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='documents_j_status_1ed09c_idx'), models.Index(fields=['celery_task_id'], name='documents_j_celery__00406b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Page number (1-indexed)')),
                ('bbox_x1', models.FloatField(help_text='Left x coordinate (normalized)')),
                ('bbox_y1', models.FloatField(help_text='Top y coordinate (normalized)')),
                ('bbox_x2', models.FloatField(help_text='Right x coordinate (normalized)')),
                ('bbox_y2', models.FloatField(help_text='Bottom y coordinate (normalized)')),
                ('element_type', models.CharField(choices=[('title', 'Title'), ('plain_text', 'Plain Text'), ('abandon', 'Abandon'), ('figure', 'Figure'), ('figure_caption', 'Figure Caption'), ('table', 'Table'), ('table_caption', 'Table Caption'), ('table_footnote', 'Table Footnote'), ('isolate_formula', 'Isolated Formula'), ('formula_caption', 'Formula Caption')], max_length=50)),
                ('confidence', models.FloatField(help_text='Detection confidence (0-1)')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('minio_image_key', models.CharField(blank=True, help_text='Reference to cropped region image in step4', max_length=500, null=True)),
                ('sequence', models.IntegerField(help_text='Reading order within page')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='documents.documentjob')),
            ],
            options={
                'db_table': 'documents_element',
                'ordering': ['job', 'page_number', 'sequence'],
                'indexes': [models.Index(fields=['job', 'page_number'], name='documents_e_job_id_1b00af_idx'), models.Index(fields=['element_type'], name='documents_e_element_a73733_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('UPLOAD', 'Upload'), ('PDF_TO_IMAGES', 'PDF to Images'), ('ML_INFERENCE', 'ML Inference'), ('DRAW_BOUNDING_BOXES', 'Draw Bounding Boxes'), ('TEXT_EXTRACTION', 'Text Extraction'), ('ASSEMBLE_GRAPH', 'Assemble Graph')], max_length=50)),
                ('step_order', models.IntegerField(help_text='Sequential order of step execution')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_current', models.IntegerField(default=0, help_text='Current progress (e.g., pages processed)')),
                ('progress_total', models.IntegerField(blank=True, help_text='Total items to process (e.g., total pages)', null=True)),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Progress as percentage (0-100)')),
                ('result_data', models.JSONField(blank=True, help_text='Step-specific output data for recovery', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('celery_task_id', models.CharField(blank=True, help_text='Individual step Celery task ID', max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documents.documentjob')),
            ],
            options={
                'db_table': 'documents_processing_step',
                'ordering': ['step_order'],
                'indexes': [models.Index(fields=['job', 'status'], name='documents_p_job_id_ec5523_idx'), models.Index(fields=['step_name', 'status'], name='documents_p_step_na_dd5b15_idx'), models.Index(fields=['status', 'started_at'], name='documents_p_status_548299_idx')],
                'unique_together': {('job', 'step_name')},
            },
        ),
    ]
