# Generated by Django 5.1.13 on 2025-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentjob',
            name='current_step',
            field=models.CharField(blank=True, choices=[('UPLOAD', 'Upload'), ('PDF_TO_IMAGES', 'PDF to Images'), ('ML_INFERENCE', 'ML Inference'), ('DRAW_BOUNDING_BOXES', 'Draw Bounding Boxes'), ('TEXT_EXTRACTION', 'Text Extraction'), ('POINTS_OCR', 'POINTS OCR'), ('ASSEMBLE_GRAPH', 'Assemble Graph')], max_length=50, null=True),
        ),
    ]
