# Generated by Django migrations

from django.db import migrations


def rename_step_names(apps, schema_editor):
    """Rename existing ML_INFERENCE step names to PAGE_SEGMENTATION"""
    DocumentJob = apps.get_model('documents', 'DocumentJob')
    ProcessingStep = apps.get_model('documents', 'ProcessingStep')
    
    # Update DocumentJob current_step and error_step fields
    DocumentJob.objects.filter(current_step='ML_INFERENCE').update(current_step='PAGE_SEGMENTATION')
    DocumentJob.objects.filter(error_step='ML_INFERENCE').update(error_step='PAGE_SEGMENTATION')
    
    # Update ProcessingStep step_name field
    ProcessingStep.objects.filter(step_name='ML_INFERENCE').update(step_name='PAGE_SEGMENTATION')


def reverse_rename_step_names(apps, schema_editor):
    """Reverse the rename operation (for rollback)"""
    DocumentJob = apps.get_model('documents', 'DocumentJob')
    ProcessingStep = apps.get_model('documents', 'ProcessingStep')
    
    # Reverse update DocumentJob current_step and error_step fields
    DocumentJob.objects.filter(current_step='PAGE_SEGMENTATION').update(current_step='ML_INFERENCE')
    DocumentJob.objects.filter(error_step='PAGE_SEGMENTATION').update(error_step='ML_INFERENCE')
    
    # Reverse update ProcessingStep step_name field
    ProcessingStep.objects.filter(step_name='PAGE_SEGMENTATION').update(step_name='ML_INFERENCE')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentjob_current_step'),
    ]

    operations = [
        migrations.RunPython(
            rename_step_names,
            reverse_rename_step_names,
        ),
    ]