# Generated by Django migrations

from django.db import migrations


def remove_ocr_processing_steps(apps, schema_editor):
    """Delete existing OCR_PROCESSING step records"""
    ProcessingStep = apps.get_model('documents', 'ProcessingStep')
    
    # Delete all OCR_PROCESSING steps
    deleted_count, _ = ProcessingStep.objects.filter(step_name='OCR_PROCESSING').delete()
    print(f'Deleted {deleted_count} OCR_PROCESSING step records')


def reverse_remove_ocr_processing_steps(apps, schema_editor):
    """Reverse operation (no-op since we can't recreate deleted data)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_ml_inference_to_page_segmentation'),
    ]

    operations = [
        migrations.RunPython(
            remove_ocr_processing_steps,
            reverse_remove_ocr_processing_steps,
        ),
    ]
