# Generated by Django migrations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_ocr_processing_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentelement',
            name='table_html',
            field=models.TextField(blank=True, help_text='HTML representation of table structure (for table elements)', null=True),
        ),
        migrations.AddField(
            model_name='documentelement',
            name='table_data',
            field=models.JSONField(blank=True, help_text='Structured table data as 2D array (for table elements)', null=True),
        ),
    ]
